server:
  servlet:
    context-path: /dev

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

swagger:
  url: http://localhost:8080/dev

jwt:
  secret: jwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscret
  expiration-period: 10000
