spring:
  batch:
    jdbc:
      initialize-schema: never
      isolation-level-for-create: read_committed
    job:
      enabled: false # 자동 실행 방지
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 100
        jdbc:
          time-zone: UTC
